name: release

on:
  push:
    branches:
      - main

jobs:
    cd:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read

        steps:
            - name: 対象ブランチをクローン
              uses: actions/checkout@v4

            - name: AWSの認証情報を設定
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/githubaction-ecr-push-role-arxiv-notify-bot'
                aws-region: ap-northeast-1
                role-duration-seconds: 900 

            - name: ECRにログイン
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Image Build & Push to ECR
              env:
                REPOSITORY_NAME: "arxiv-notify"
                FUNCTION_NAME: "arxiv-notify-video-summarization"
                IMAGE_TAG: "${{ github.sha }}"
              run: |
                docker build --platform linux/x86_64 -t ${{ env.REPOSITORY_NAME }} -f ./Dockerfile .
                docker tag ${{ env.REPOSITORY_NAME }}:latest ${{ secrets.AWS_ECR_ENDPOINT }}/${{ env.REPOSITORY_NAME }}:${{ env.IMAGE_TAG }}
                docker push ${{ secrets.AWS_ECR_ENDPOINT }}/${{ env.REPOSITORY_NAME }}:${{ env.IMAGE_TAG }}
                aws lambda update-function-code --function-name ${{ env.FUNCTION_NAME }} --image-uri ${{ secrets.AWS_ECR_ENDPOINT }}/${{ env.REPOSITORY_NAME }}:${{ env.IMAGE_TAG }} --region ap-northeast-1
                